config/routes.rb
Store::Application.routes.draw do

  root :to => 'products#index'

  devise_for :users, controllers: {:registrations => "users/registrations", sessions: "users/sessions"}

  match '/orders'                          => 'orders#index', via: [:get, :post], as: 'all_orders'
  match '/users/:user_id/orders'           => 'orders#list',  via: [:get, :post], as: 'orders'
  match '/users/:user_id/orders/:order_id' => 'orders#show',  via: [:get, :post], as: 'order'

  match '/:order_id/change_status'   => 'orders#change_status',   via: [:get, :post], as: 'change_order_status'
  match '/:order_id/get_next_status' => 'orders#get_next_status', via: [:get, :post], as: 'get_next_order_status'

  resources :products

  resources :carts

  get   'carts/products'              => 'carts#products'
  get   'carts/:cart_id/remove/:id'   => 'carts#remove_product',   via: [:get, :post], as: 'remove_product'
  match 'carts/:cart_id/add/:id'      => 'carts#add_product',      via: [:get, :post], as: 'add_product'
  match 'carts/:cart_id/subtract/:id' => 'carts#subtract_product', via: [:get, :post], as: 'subtract_product'

  match '/buy' => 'carts#buy', as: 'buy_cart', via: [:get, :post]

  match '/import'           => 'users#import',           via: [:get, :post], as: 'import'
  match '/import_cart'      => 'users#import_cart',      via: [:get, :post], as: 'import_cart'
  match '/dont_import_cart' => 'users#dont_import_cart', via: [:get, :post], as: 'dont_import_cart'

  match '/minus_quantity' => 'carts#minus_quantity', via: [:get, :post]
  match '/plus_quantity'  => 'carts#plus_quantity',  via: [:get, :post]

  match '/minus_quantity/:id' => 'carts#minus_quantity', via: [:get, :post]
  match '/plus_quantity/:id'  => 'carts#plus_quantity',  via: [:get, :post]

  match '/new_tag'            => 'tags#new',    via: [:get, :post]
  match '/tags/:tag_id'       => 'tags#show',   via: [:get], as: "tag"
  match '/delete_tag/:tag_id' => 'tags#delete', via: [:post],as: "delete_tag"
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :orders_products, dependent: :destroy
  has_many :products, through: :orders_products
  validates :orders_products,
    length: {minimum: 1, message: 'You must have at least one product in your Cart to buy it'}
  validates :user_id, presence: {message: 'You must be logged in to buy a Cart'}

  def self.check (user, cart_id)
    cart = Cart.find cart_id
    order = Order.new status: 'Awaiting payment'
    order.user_id = user.id if user
    if !cart.carts_products.empty?
      cart.carts_products.each do |carts_product|
        q = carts_product.quantity
        order.orders_products.build( product_id: carts_product.product_id, quantity: q ) if q and q > 0
      end
      cart.destroy if order.save
    end
    return order
  end


  def get_next_status
    case self.status
    when "Awaiting payment"
      return "Awaiting shipment"
    when "Awaiting shipment"
      return "Shipped"
    when "Shipped"
      return "Received"
    else
      return "Awaiting payment"
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :check_visibility, only: [:change_status, :show]

  def index
    if current_user and current_user.admin
      @orders = Order.all
    else
      flash[:notice] = 'You must be Admin to access this page'
      redirect_to root_path
    end
  end

  def test_user_permission (&block)
    if current_user
      if current_user.id == params[:user_id].to_i or current_user.admin
        block.call
      else
        flash[:notice] = "You don't have permission to access this page"
        redirect_to root_path
      end
    else
      flash[:notice] = "You must login to view this page"
      redirect_to new_user_session_path
    end
  end

  def show
    test_user_permission { @order = Order.find params[:order_id] }
  end

  def list
    test_user_permission { @orders = Order.where user: current_user }
  end

  def check_visibility
    order = Order.find params[:order_id]
    # debugger
    if (current_user.admin and order.status != 'Shipped' and order.status != 'Received') or
       (current_user == order.user and order.status=='Shipped' and order.status != 'Received')
      @visible_button = true
    else
      @visible_button = false
    end
  end

  def change_status
    order = Order.find params[:order_id]
    order.status = order.get_next_status
    order.save
    check_visibility
    render json: { order_status: order.status, next_order_status: order.get_next_status, visible: @visible_button }
  end
end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/orders/index.html.erb
<h1>Listing all existing Orders</h1>

<table id="all_orders">
<tr>
  <td align='Center'><strong>Order #</strong></td>
  <td align='Center'><strong>User</strong></td>
  <td align='Center'><strong>Created at</strong></td>
  <td align='Center'><strong>Status</strong></td>
</tr>
  <% for order in @orders do %>
    <tr>
      <td align='Center'><%= link_to order.id, order_path(order.user, order) %></td>
      <td align='Center'><%= order.user.name %></td>
      <td align='Center'><%= order.created_at.to_date %></td>
      <td align='Center'><%= order.status%></td>
    </tr>
  <% end %>

</table>

app/views/orders/list.html.erb
<h1>Listing all Orders</h1>

<table id="orders">
<tr>
  <td align='Center'><strong>Order #</strong></td>
  <td align='Center'><strong>Created at</strong></td>
  <td align='Center'><strong>Status</strong></td>
  <td align='Center'><% link_to  %></td>
</tr>
  <% for order in @orders do %>
    <tr>
      <td align='Center'><%= link_to order.id, order_path(order.user, order) %></td>
      <td align='Center'><%= order.created_at.to_date %></td>
      <td align='Center'><%= order.status%></td>
    </tr>
  <% end %>

</table>

app/views/orders/show.html.erb
<h1>Details of Order</h1>

<table id="order">
  <tr>
    <td><strong>Order #:</strong></td>
    <td><%= @order.id %></td>
  </tr>
  <tr>
    <td><strong>Created at:</strong></td>
    <td><%= @order.created_at.to_date %></td>
  </tr>
  <tr id='status-line'>
    <td><strong>Status:</strong></td>
    <td id='status'> <%= @order.status %> </td>
    <% if @visible_button %>
      <td><button id='change' data-id=<%= @order.id %> data-visible=<%= @visible_button %>>Change to '<%= @order.get_next_status %>'</button></td>
    <% end %>
  </tr>
</table>


<table id="products">
  <tr>
    <td><h3>Products:</h3></td>
  </tr>
  <tr>
    <td><strong>Name</strong></td>
    <td><strong>Quantity</strong></td>
  </tr>
    <% for product in @order.products %>
      <tr>
        <td><%= product.name %></td>
        <td align='center'><%= OrdersProduct.find_by(order_id: @order.id, product_id: product.id).quantity %></td>
      </tr>
    <% end %>
</table>