config/routes.rb
Store::Application.routes.draw do

  root :to => 'products#index'

  devise_for :users, controllers: {:registrations => "users/registrations", sessions: "users/sessions"}

  match '/orders'                          => 'orders#index', via: [:get, :post], as: 'all_orders'
  match '/users/:user_id/orders'           => 'orders#list',  via: [:get, :post], as: 'orders'
  match '/users/:user_id/orders/:order_id' => 'orders#show',  via: [:get, :post], as: 'order'

  match '/:order_id/change_status'   => 'orders#change_status',   via: [:get, :post], as: 'change_order_status'
  match '/:order_id/get_next_status' => 'orders#get_next_status', via: [:get, :post], as: 'get_next_order_status'

  resources :products

  resources :carts

  get   'carts/products'              => 'carts#products'
  get   'carts/:cart_id/remove/:id'   => 'carts#remove_product',   via: [:get, :post], as: 'remove_product'
  match 'carts/:cart_id/add/:id'      => 'carts#add_product',      via: [:get, :post], as: 'add_product'
  match 'carts/:cart_id/subtract/:id' => 'carts#subtract_product', via: [:get, :post], as: 'subtract_product'

  match '/buy' => 'carts#buy', as: 'buy_cart', via: [:get, :post]

  match '/import'           => 'users#import',           via: [:get, :post], as: 'import'
  match '/import_cart'      => 'users#import_cart',      via: [:get, :post], as: 'import_cart'
  match '/dont_import_cart' => 'users#dont_import_cart', via: [:get, :post], as: 'dont_import_cart'

  match '/minus_quantity' => 'carts#minus_quantity', via: [:get, :post]
  match '/plus_quantity'  => 'carts#plus_quantity',  via: [:get, :post]

  match '/minus_quantity/:id' => 'carts#minus_quantity', via: [:get, :post]
  match '/plus_quantity/:id'  => 'carts#plus_quantity',  via: [:get, :post]

  match '/new_tag'            => 'tags#new',    via: [:get, :post]
  match '/tags/:tag_id'       => 'tags#show',   via: [:get], as: "tag"
  match '/delete_tag/:tag_id' => 'tags#delete', via: [:post],as: "delete_tag"
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_one :user
  has_many :carts_products, dependent: :destroy
  has_many :products, through: :carts_products
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, except: [:buy, :cart_params]

  def edit
  end

  def buy
    @order = Order.check( current_user, session[:cart_id] )
    if @order.valid?
      @cart = Cart.create
      session[:cart_id] = @cart.id
      current_user.cart = @cart
      current_user.save
      flash[:buy] = "You bought the Cart."
      redirect_to products_path
    else
      flash[:buy] = @order.errors.messages.to_a[0][1][0]
      if flash[:buy] == 'You must be logged in to buy a Cart'
        redirect_to new_user_session_path
      else
        redirect_to products_path
      end
    end
  end

  def set_cart
    @cart = Cart.find(session[:cart_id])
    @carts_products = @cart.carts_products
    @sum = 0
    @carts_products.each { |cp| @sum += cp.quantity }
  end

  def carts_product_quantity
    Product.all.map { |p|
      if CartsProduct.where(cart_id: @cart.id).map{|cp| cp.product_id}.include? p.id
        CartsProduct.find_by(cart_id: @cart.id, product_id: p.id).quantity
      else
        0
      end
    }
  end

  def products
    respond_to do |format|
      format.json { render json: CartsProduct.where(cart_id: @cart.id).to_json }
      format.html {}
    end
  end

  def remove_product
    @carts_products.where( product_id: params[:id]).destroy_all
    redirect_to cart_path(session[:cart_id])
  end

  def cart_params
    params.require(:cart).permit(:cart_id, product_ids: [])
  end

  def minus_quantity
    @carts_product = CartsProduct.find_by(cart_id: session[:cart_id], product_id: params[:id])
    if @carts_product
      @carts_product.quantity -= 1 if @carts_product.quantity > 0
      @carts_product.quantity = 0  if @carts_product.quantity < 0
      @carts_product.save
      render json: @carts_product.quantity
    else
      render json: {}
    end
  end

  def plus_quantity
    @carts_product = CartsProduct.find_by(cart_id: session[:cart_id], product_id: params[:id])
    if @carts_product
      @carts_product.quantity += 1
      @carts_product.save
    else
      @carts_product = CartsProduct.create( cart_id: session[:cart_id],
        product_id: Product.find(params[:id]).id, quantity: 1)
    end
    render json: @carts_product.quantity
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/carts/_form.html.erb
<%= form_for @cart do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :products %><br>
    <% Product.all.collect do |a| %>
      <%= f.check_box :product_ids, {:multiple => true}, a.id, nil %>
      <%= a.name %>
      <br>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Form for New User</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %><br>

app/views/carts/import.hml.erb
<h1>You have a saved Cart</h1>

Do you want to import it?

<%= button_to 'Import', import_cart_path %>
<%= button_to "Don't import", dont_import_cart_path %>

app/views/carts/new.html.erb
<h1>Form for New Cart</h1>

<% c = Cart.new %>
<% c.user_id = @user.id %>
<% c.save %>
Cart created successfully
<%= link_to 'Back', user_carts_path(params[:user_id]) %>

app/views/carts/show.html.erb
<h1>Showing details of cart</h1>
<br>

<table>
  <tr>
    <td><strong>Product name:</strong></td>
    <td><strong>Price:</strong></td>
    <td><strong>Description:</strong></td>
    <td><strong>#</strong> </td>
    <td><strong>Total:</strong> </td>
  </tr>

  <tr ng-repeat="product in products" ng-show="product.quantity">
    <td class="product-name">
      {{product.name}}
    </td>
    <td class="product-price">
      {{product.price | number: 2}}
    </td>
    <td class="product-description">
      {{product.description}}
    </td>

    <td class="product-buttons" cart-buttons="{{product.id}}">
    </td>

    <td class="product-name">
      {{product.total | number: 2}}
    </td>
    <td>
      <a class="btn btn-danger btn-mini" href="/carts/<%= @cart.id %>/remove/{{product.id}}">Remover produto</a>
    </td>
  </tr>


  <tr><td></td><td><td></td><td></td><td><hr></td></tr>
  <tr><td></td><td></td><td></td><td></td><td>{{total | number: 2}}</td>
  </tr>
</table>
<br>




<%= link_to 'Buy this Cart', buy_cart_path(session[:cart_id]), data:{  :confirm => "Confirm?" }, class: :btn %><br>
<%= link_to 'Add Products', products_path, class: :btn %><br>