config/routes.rb
Store::Application.routes.draw do

  root :to => 'products#index'

  devise_for :users, controllers: {:registrations => "users/registrations", sessions: "users/sessions"}

  match '/orders'                          => 'orders#index', via: [:get, :post], as: 'all_orders'
  match '/users/:user_id/orders'           => 'orders#list',  via: [:get, :post], as: 'orders'
  match '/users/:user_id/orders/:order_id' => 'orders#show',  via: [:get, :post], as: 'order'

  match '/:order_id/change_status'   => 'orders#change_status',   via: [:get, :post], as: 'change_order_status'
  match '/:order_id/get_next_status' => 'orders#get_next_status', via: [:get, :post], as: 'get_next_order_status'

  resources :products

  resources :carts

  get   'carts/products'              => 'carts#products'
  get   'carts/:cart_id/remove/:id'   => 'carts#remove_product',   via: [:get, :post], as: 'remove_product'
  match 'carts/:cart_id/add/:id'      => 'carts#add_product',      via: [:get, :post], as: 'add_product'
  match 'carts/:cart_id/subtract/:id' => 'carts#subtract_product', via: [:get, :post], as: 'subtract_product'

  match '/buy' => 'carts#buy', as: 'buy_cart', via: [:get, :post]

  match '/import'           => 'users#import',           via: [:get, :post], as: 'import'
  match '/import_cart'      => 'users#import_cart',      via: [:get, :post], as: 'import_cart'
  match '/dont_import_cart' => 'users#dont_import_cart', via: [:get, :post], as: 'dont_import_cart'

  match '/minus_quantity' => 'carts#minus_quantity', via: [:get, :post]
  match '/plus_quantity'  => 'carts#plus_quantity',  via: [:get, :post]

  match '/minus_quantity/:id' => 'carts#minus_quantity', via: [:get, :post]
  match '/plus_quantity/:id'  => 'carts#plus_quantity',  via: [:get, :post]

  match '/new_tag'            => 'tags#new',    via: [:get, :post]
  match '/tags/:tag_id'       => 'tags#show',   via: [:get], as: "tag"
  match '/delete_tag/:tag_id' => 'tags#delete', via: [:post],as: "delete_tag"
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_and_belongs_to_many :tags
  has_many :carts_products
  has_many :carts, through: :carts_products
  has_many :orders_products
  has_many :orders, through: :orders_products
  validates :name, presence: true, uniqueness: true
  validates :price, presence: true

  attr_accessor :quantity
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all.as_json

    @products.map { |product|
      product['quantity'] = current_user.cart.carts_products.find_by(product_id: product['id']).try(:quantity)
      product['total'] = product['quantity'].to_i * product['price'].to_f
    }


    respond_to do |format|
      format.html
      format.json { render json: @products }
    end
  end

  def new
    @product = Product.new
    if (current_user and current_user.admin == false) or !current_user
      flash[:notice] = "You must be logged as admin to enter this page"
      redirect_to root_path
    end
  end

  def create
    @product = Product.new (product_params)
    if @product.save
      flash[:notice] = "Product created successfully"
    end
    redirect_to root_path
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :price, :description)
  end
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product_details.html.erb
<% carts_product = CartsProduct.find_by(cart_id: session[:cart_id], product_id: product.id) %>
<td>
  <%= product.name %></td>
<td align=right>
  <%= number_to_currency product.price, unit: '' %>
</td>
<td>
  <%= button_to 'View product details', product_path(product.id), method: :get %>
</td>
<td>
  <button class='mp' data-operation='minus' data-id='<%= product.id %>' data-price='<%= product.price %>'>
    -
  </button>
</td>
<td>
  <div id="div<%= product.id %>">
    <%= if carts_product then carts_product.quantity else 0 end %>
  </div>
</td>
<td>
  <button class='mp' data-operation='plus'  data-id='<%= product.id %>' data-price='<%= product.price %>'>
    +
  </button>
</td>

app/views/products/create.html.erb
<!-- <h1>Product created</h1> -->

app/views/products/index.html.erb
<h1>Listing all products</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th>Description</th>
    <th>Quantity</th>
    <th></th>
  </tr>
  <tr ng-repeat="product in products">
    <td class="product-name">
      {{product.name}}
    </td>
    <td class="product-price">
      {{product.price | number: 2}}
    </td>
    <td class="product-details">
      {{product.description}}
    </td>
    <td class="product-buttons" cart-buttons="{{product.id}}"></td>
    <td class="product-view">
      <a href="/products/{{product.id}}" class="btn">View product details</a>
    </td>
  </tr>
</table>

<%= link_to 'View the Cart', cart_path(session[:cart_id]), class: :btn %>
<%= link_to 'Buy this Cart', buy_cart_path(session[:cart_id]), data:{:confirm => "Confirm?"}, class: :btn %>
<% if current_user %>
  <%= link_to 'View my Orders', orders_path(current_user), class: :btn %>
  <% if current_user.admin %>
    <%= link_to 'View all Orders', all_orders_path, class: :btn %>
    <%= link_to 'New product', new_product_path, class: :btn %>
  <% end %>
<% end %>

app/views/products/new.html.erb
<h1>Form for New Product</h1>
<%= render 'form' %>
<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<h1 id='<%= @product.id %>'>Showing details of product</h1>

<div>Name:</div>
<div><%= @product.name %></div>
<br>
<div>Price:</div>
<div><%= number_to_currency @product.price, unit: '' %></div>
<br>
<div>Description:</div>
<div><%= @product.description %></div>
<br>
<div id='AllTags'>
  Tags:
  <div id='Tags'>
    <% @product.tags.each do |t| %>
      <%= button_to t.name, tag_path(t), class: :tags, method: :get %>
    <% end %>
  </div>
  <% if current_user and current_user.admin %>
    <button id="AddTag">Add Tag</button>
    <input type="text" id="TagName">
  <% end %>
</div>